# Generated by Django 3.2.3 on 2021-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('datanascimento', models.DateField()),
                ('datacadastro', models.DateTimeField(auto_now=True)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('indefinido', 'Indefinido')], default='feminino', max_length=10)),
                ('rg', models.CharField(blank=True, max_length=12)),
                ('cpf', models.CharField(blank=True, max_length=12)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=150)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('fone1', models.CharField(blank=True, max_length=20)),
                ('fone2', models.CharField(blank=True, max_length=20)),
                ('fone3', models.CharField(blank=True, max_length=20)),
                ('fone4', models.CharField(blank=True, max_length=20)),
                ('contatoemergencia', models.CharField(max_length=150)),
                ('parentesco', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('escolaridade', models.CharField(choices=[('fundai', 'Fundamental Incompleto'), ('fundac', 'Fundamental Completo'), ('medioi', 'Ensino Médio Completo'), ('medioc', 'Ensino Médio Incompleto'), ('superi', 'Superior Incompleto'), ('superc', 'Superior Completo'), ('posgra', 'Pós-Graduação')], default='fundai', max_length=6)),
                ('faculdade', models.CharField(blank=True, max_length=150)),
                ('disponibilidade', models.CharField(choices=[('manha', 'Horário Manhã'), ('tarde', 'Horário Tarde'), ('noite', 'Horário Noite'), ('final', 'Final de Semana'), ('flexi', 'Flexível')], default='flexi', max_length=5)),
                ('autorizacao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=False)),
                ('irig', models.BooleanField(default=False)),
                ('contatopf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contatopf.contatopf', verbose_name='Reporter_ContatoPF')),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField(blank=True)),
                ('manequim', models.IntegerField(blank=True)),
                ('calcado', models.IntegerField(blank=True)),
                ('contatopf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contatopf.contatopf', verbose_name='Promotor_ContatoPF')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('categoriaa', 'Categoria A'), ('categoriab', 'Categoria B'), ('categoriac', 'Categoria C'), ('categoriae', 'Categoria E')], default='categoriab', max_length=10)),
                ('datahabilitacao', models.DateField()),
                ('validadehabilitacao', models.DateField()),
                ('contatopf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contatopf.contatopf', verbose_name='Motorista_ContatoPF')),
            ],
        ),
    ]
