# Generated by Django 3.2.3 on 2021-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatopf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatopf',
            name='fone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contatopf',
            name='fone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contatopf',
            name='fone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contatopf',
            name='fone4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
