# Generated by Django 3.2.3 on 2021-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatopf', '0002_auto_20210520_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
