# Generated by Django 3.2.3 on 2021-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatopf', '0002_auto_20210517_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatopf',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
    ]
