# Generated by Django 3.2.3 on 2021-05-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatopf', '0003_precadastro_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='bairro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='evento',
            name='contato1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contato2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contato3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contato4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evento',
            name='fone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fone4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='DataEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataevento', models.DateField()),
                ('confirmado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contatopf.evento', verbose_name='DataEvento_Evento')),
            ],
        ),
    ]
