# Generated by Django 3.2.3 on 2021-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatopf', '0004_auto_20210521_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='endereco',
        ),
        migrations.AddField(
            model_name='dataevento',
            name='bairro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dataevento',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dataevento',
            name='cidade',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dataevento',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataevento',
            name='observacoes',
            field=models.TextField(null=True),
        ),
    ]
