# Generated by Django 3.2.3 on 2021-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('datanascimento', models.DateField()),
                ('datacadastro', models.DateTimeField(auto_now=True)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('indefinido', 'Indefinido')], default='feminino', max_length=10)),
                ('rg', models.CharField(blank=True, max_length=12)),
                ('cpf', models.CharField(blank=True, max_length=12)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=150)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('fone1', models.CharField(blank=True, max_length=20)),
                ('fone2', models.CharField(blank=True, max_length=20)),
                ('fone3', models.CharField(blank=True, max_length=20)),
                ('fone4', models.CharField(blank=True, max_length=20)),
                ('contatoemergencia', models.CharField(max_length=150)),
                ('parentesco', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('altura', models.IntegerField(blank=True)),
                ('manequim', models.IntegerField(blank=True)),
                ('calcado', models.IntegerField(blank=True)),
                ('escolaridade', models.CharField(choices=[('fundai', 'Fundamental Incompleto'), ('fundac', 'Fundamental Completo'), ('medioi', 'Ensino Médio Completo'), ('medioc', 'Ensino Médio Incompleto'), ('superi', 'Superior Incompleto'), ('superc', 'Superior Completo'), ('posgra', 'Pós-Graduação')], default='fundai', max_length=6)),
                ('faculdade', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
